export const MAIN_PATH = ()=>'/'
export const SIGN_UP_PATH = ()=>'/auth/sign-up'
export const SIGN_IN_PATH = ()=>'/auth/sign-in'
export const SEARCH_PATH = (searchWord)=>`/search/${searchWord}`
export const USER_PATH = (userId)=>`/user/${userId}`
export const STUDY_PATH = ()=>'/study'
export const STUDY_DETAIL_PATH = (studyNumber)=>`detail/${studyNumber}`
export const STUDY_WRITE_PATH = (searchWord)=>'write'
export const STUDY_UPDATE_PATH = (studyNumber)=>`update/${studyNumber}`